// User Module
const GET_USERS_DATA_INIT = "GET_USERS_DATA_INIT";
const GET_USERS_DATA_SUCCESS = "GET_USERS_DATA_SUCCESS";
const GET_USERS_DATA_ERROR = "GET_USERS_DATA_ERROR";

const GET_USERS_DEPARTMENTS_INIT = "GET_USERS_DEPARTMENTS_INIT";
const GET_USERS_DEPARTMENTS_SUCCESS = "GET_USERS_DEPARTMENTS_SUCCESS";
const GET_USERS_DEPARTMENTS_ERROR = "GET_USERS_DEPARTMENTS_ERROR";

const ADD_USERS_DATA_INIT = "ADD_USERS_DATA_INIT";
const ADD_USERS_DATA_SUCCESS = "ADD_USERS_DATA_SUCCESS";
const ADD_USERS_DATA_ERROR = "ADD_USERS_DATA_ERROR";

const EDIT_USERS_INIT = "EDIT_USERS_INIT";
const EDIT_USERS_SUCCESS = "EDIT_USERS_SUCCESS";
const EDIT_USERS_ERROR = "EDIT_USERS_ERROR";

const GET_USERS_PERMISSION_INIT = "GET_USERS_PERMISSION_INIT";
const GET_USERS_PERMISSION_SUCCESS = "GET_USERS_PERMISSION_SUCCESS";
const GET_USERS_PERMISSION_ERROR = "GET_USERS_PERMISSION_ERROR";

const UPDATE_USERS_INIT = "UPDATE_USERS_INIT";
const UPDATE_USERS_SUCCESS = "UPDATE_USERS_SUCCESS";
const UPDATE_USERS_ERROR = "UPDATE_USERS_ERROR";

const IMPORT_PIC_FILE_INIT = "IMPORT_PIC_FILE_INIT";
const IMPORT_PIC_FILE_SUCCESS = "IMPORT_PIC_FILE_SUCCESS";
const IMPORT_PIC_FILE_ERROR = "IMPORT_PIC_FILE_ERROR";

const GET_USERS_AUTOCOMPLETE_INIT = "GET_USERS_AUTOCOMPLETE_INIT";
const GET_USERS_AUTOCOMPLETE_SUCCESS = "GET_USERS_AUTOCOMPLETE_SUCCESS";
const GET_USERS_AUTOCOMPLETE_ERROR = "GET_USERS_AUTOCOMPLETE_ERROR";

const UPDATE_USER_ISACTIVE_INIT = "UPDATE_USER_ISACTIVE_INIT";
const UPDATE_USER_ISACTIVE_SUCCESS = "UPDATE_USER_ISACTIVE_SUCCESS";
const UPDATE_USER_ISACTIVE_ERROR = "UPDATE_USER_ISACTIVE_ERROR";

// Department Module
const GET_DEPARTMENTS_INIT = "GET_DEPARTMENTS_INIT";
const GET_DEPARTMENTS_SUCCESS = "GET_DEPARTMENTS_SUCCESS";
const GET_DEPARTMENTS_ERROR = "GET_DEPARTMENTS_ERROR";

const ADD_DEPARTMENTS_INIT = "ADD_DEPARTMENTS_INIT";
const ADD_DEPARTMENTS_SUCCESS = "ADD_DEPARTMENTS_SUCCESS";
const ADD_DEPARTMENTS_ERROR = "ADD_DEPARTMENTS_ERROR";

const GET_DEPARTMENTS_BY_ID_INIT = "GET_DEPARTMENTS_BY_ID_INIT";
const GET_DEPARTMENTS_BY_ID_SUCCESS = "GET_DEPARTMENTS_BY_ID_SUCCESS";
const GET_DEPARTMENTS_BY_ID_ERROR = "GET_DEPARTMENTS_BY_ID_ERROR";

const EDIT_DEPARTMENTS_INIT = "EDIT_DEPARTMENTS_INIT";
const EDIT_DEPARTMENTS_SUCCESS = "EDIT_DEPARTMENTS_SUCCESS";
const EDIT_DEPARTMENTS_ERROR = "EDIT_DEPARTMENTS_ERROR";

const UPDATE_DEPT_ISACTIVE_INIT = "UPDATE_DEPT_ISACTIVE_INIT";
const UPDATE_DEPT_ISACTIVE_SUCCESS = "UPDATE_DEPT_ISACTIVE_SUCCESS";
const UPDATE_DEPT_ISACTIVE_ERROR = "UPDATE_DEPT_ISACTIVE_ERROR";

// Performance Main Parameter
const GET_PERFORMANCE_INIT = "GET_PERFORMANCE_INIT";
const GET_PERFORMANCE_SUCCESS = "GET_PERFORMANCE_SUCCESS";
const GET_PERFORMANCE_ERROR = "GET_PERFORMANCE_ERROR";

const ADD_PERFORMANCE_INIT = "ADD_PERFORMANCE_INIT";
const ADD_PERFORMANCE_SUCCESS = "ADD_PERFORMANCE_SUCCESS";
const ADD_PERFORMANCE_ERROR = "ADD_PERFORMANCE_ERROR";

const GET_PERFORMANCE_BY_ID_INIT = "GET_PERFORMANCE_BY_ID_INIT";
const GET_PERFORMANCE_BY_ID_SUCCESS = "GET_PERFORMANCE_BY_ID_SUCCESS";
const GET_PERFORMANCE_BY_ID_ERROR = "GET_PERFORMANCE_BY_ID_ERROR";

const EDIT_PERFORMANCE_INIT = "EDIT_PERFORMANCE_INIT";
const EDIT_PERFORMANCE_SUCCESS = "EDIT_PERFORMANCE_SUCCESS";
const EDIT_PERFORMANCE_ERROR = "EDIT_PERFORMANCE_ERROR";

const UPDATE_PER_ISACTIVE_INIT = "UPDATE_PER_ISACTIVE_INIT";
const UPDATE_PER_ISACTIVE_SUCCESS = "UPDATE_PER_ISACTIVE_SUCCESS";
const UPDATE_PER_ISACTIVE_ERROR = "UPDATE_PER_ISACTIVE_ERROR";

// Sub Performance
const GET_SUBPERFORMANCE_INIT = "GET_SUBPERFORMANCE_INIT";
const GET_SUBPERFORMANCE_SUCCESS = "GET_SUBPERFORMANCE_SUCCESS";
const GET_SUBPERFORMANCE_ERROR = "GET_SUBPERFORMANCE_ERROR";

const ADD_SUBPERFORMANCE_INIT = "ADD_SUBPERFORMANCE_INIT";
const ADD_SUBPERFORMANCE_SUCCESS = "ADD_SUBPERFORMANCE_SUCCESS";
const ADD_SUBPERFORMANCE_ERROR = "ADD_SUBPERFORMANCE_ERROR";

const EDIT_SUBPERFORMANCE_INIT = "EDIT_SUBPERFORMANCE_INIT";
const EDIT_SUBPERFORMANCE_SUCCESS = "EDIT_SUBPERFORMANCE_SUCCESS";
const EDIT_SUBPERFORMANCE_ERROR = "EDIT_SUBPERFORMANCE_ERROR";

const GET_SUBPERFORMANCE_BY_ID_INIT = "GET_SUBPERFORMANCE_BY_ID_INIT";
const GET_SUBPERFORMANCE_BY_ID_SUCCESS = "GET_SUBPERFORMANCE_BY_ID_SUCCESS";
const GET_SUBPERFORMANCE_BY_ID_ERROR = "GET_SUBPERFORMANCE_BY_ID_ERROR";

// Evaluation
const GET_CALCULATION_INIT = "GET_PERFORMANCE_ID_INIT";
const GET_CALCULATION_SUCCESS = "GET_PERFORMANCE_ID_SUCCESS";
const GET_CALCULATION_ERROR = "GET_PERFORMANCE_ID_ERROR";

const SAVE_CALCULATION_INIT = "SAVE_PERFORMANCE_ID_INIT";
const SAVE_CALCULATION_SUCCESS = "SAVE_PERFORMANCE_ID_SUCCESS";
const SAVE_CALCULATION_ERROR = "SAVE_PERFORMANCE_ID_ERROR";

// Mom Modules
const GET_MOM_INIT = "GET_MOM_INIT";
const GET_MOM_SUCCESS = "GET_MOM_SUCCESS";
const GET_MOM_ERROR = "GET_MOM_ERROR";

const SUBMIT_MOM_INIT = "SUBMIT_MOM_INIT";
const SUBMIT_MOM_SUCCESS = "SUBMIT_MOM_SUCCESS";
const SUBMIT_MOM_ERROR = "SUBMIT_MOM_ERROR";

const EDIT_MOM_DATA_INIT = "EDIT_MOM_DATA_INIT";
const EDIT_MOM_DATA_SUCCESS = "EDIT_MOM_DATA_SUCCESS";
const EDIT_MOM_DATA_ERROR = "EDIT_MOM_DATA_ERROR";

// Time Log
const ADD_CHECKIN_INIT = "ADD_CHECKIN_INIT";
const ADD_CHECKIN_SUCCESS = "ADD_CHECKIN_SUCCESS";
const ADD_CHECKIN_ERROR = "ADD_CHECKIN_ERROR";

const UPDATE_CHECKOUT_INIT = "UPDATE_CHECKOUT_INIT";
const UPDATE_CHECKOUT_SUCCESS = "UPDATE_CHECKOUT_SUCCESS";
const UPDATE_CHECKOUT_ERROR = "UPDATE_CHECKOUT_ERROR";

const GET_TIME_TABLE_INIT = "GET_TIME_TABLE_INIT";
const GET_TIME_TABLE_SUCCESS = "GET_TIME_TABLE_SUCCESS";
const GET_TIME_TABLE_ERROR = "GET_TIME_TABLE_ERROR";

// Sales Module
const PROPOSAL_SUBMISSION_INIT = "PROPOSAL_SUBMISSION_INIT";
const PROPOSAL_SUBMISSION_SUCCESS = "PROPOSAL_SUBMISSION_SUCCESS";
const PROPOSAL_SUBMISSION_ERROR = "PROPOSAL_SUBMISSION_ERROR";

const POST_PROPOSAL_SUBMIT_INIT = "POST_PROPOSAL_SUBMIT_INIT";
const POST_PROPOSAL_SUBMIT_SUCCESS = "POST_PROPOSAL_SUBMIT_SUCCESS";
const POST_PROPOSAL_SUBMIT_ERROR = "POST_PROPOSAL_SUBMIT_ERROR";

const GET_PROPOSAL_BY_ID_INIT = "GET_PROPOSAL_BY_ID_INIT";
const GET_PROPOSAL_BY_ID_SUCCESS = "GET_PROPOSAL_BY_ID_SUCCESS";
const GET_PROPOSAL_BY_ID_ERROR = "GET_PROPOSAL_BY_ID_ERROR";

const UPLOAD_PROPOSAL_INIT = "UPLOAD_PROPOSAL_INIT";
const UPLOAD_PROPOSAL_SUCCESS = "UPLOAD_PROPOSAL_SUCCESS";
const UPLOAD_PROPOSAL_ERROR = "UPLOAD_PROPOSAL_ERROR";

const UPDATE_STATUS_INIT = "UPDATE_STATUS_INIT";
const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
const UPDATE_STATUS_ERROR = "UPDATE_STATUS_ERROR";

const GET_SALES_DROPDOWN_INIT = "GET_SALES_DROPDOWN_INIT";
const GET_SALES_DROPDOWN_SUCCESS = "GET_SALES_DROPDOWN_SUCCESS";
const GET_SALES_DROPDOWN_ERROR = "GET_SALES_DROPDOWN_ERROR";

const BUTTON_SELECT_STATUS_INIT = "BUTTON_SELECT_STATUS_INIT";
const BUTTON_SELECT_STATUS_SUCCESS = "BUTTON_SELECT_STATUS_SUCCESS";
const BUTTON_SELECT_STATUS_ERROR = "BUTTON_SELECT_STATUS_ERROR";

const DELETE_ACTIVE_STATUS_INIT = "DELETE_ACTIVE_STATUS_INIT";
const DELETE_ACTIVE_STATUS_SUCCESS = "DELETE_ACTIVE_STATUS_SUCCESS";
const DELETE_ACTIVE_STATUS_ERROR = "DELETE_ACTIVE_STATUS_ERROR";

const GET_SALES_TARGET_INIT = "GET_SALES_TARGET_INIT";
const GET_SALES_TARGET_SUCCESS = "GET_SALES_TARGET_SUCCESS";
const GET_SALES_TARGET_ERROR = "GET_SALES_TARGET_ERROR";

const IMPORT_CSV_FILE_INIT = "IMPORT_CSV_FILE_INIT";
const IMPORT_CSV_FILE_SUCCESS = "IMPORT_CSV_FILE_SUCCESS";
const IMPORT_CSV_FILE_ERROR = "IMPORT_CSV_FILE_ERROR";

const GET_SALES_TARGET_BY_ID_INIT = "GET_SALES_TARGET_BY_ID_INIT";
const GET_SALES_TARGET_BY_ID_SUCCESS = "GET_SALES_TARGET_BY_ID_SUCCESS";
const GET_SALES_TARGET_BY_ID_ERROR = "GET_SALES_TARGET_BY_ID_ERROR";

// Revenue Report
const GET_REVENUE_DATA_INIT = "GET_REVENUE_DATA_INIT";
const GET_REVENUE_DATA_SUCCESS = "GET_REVENUE_DATA_SUCCESS";
const GET_REVENUE_DATA_ERROR = "GET_REVENUE_DATA_ERROR";

const ADD_REVENUE_DATA_INIT = "ADD_REVENUE_DATA_INIT";
const ADD_REVENUE_DATA_SUCCESS = "ADD_REVENUE_DATA_SUCCESS";
const ADD_REVENUE_DATA_ERROR = "ADD_REVENUE_DATA_ERROR";

const GET_REVENUE_BY_ID_INIT = "GET_REVENUE_BY_ID_INIT";
const GET_REVENUE_BY_ID_SUCCESS = "GET_REVENUE_BY_ID_SUCCESS";
const GET_REVENUE_BY_ID_ERROR = "GET_REVENUE_BY_ID_ERROR";

const EDIT_REVENUE_DATA_INIT = "EDIT_REVENUE_DATA_INIT";
const EDIT_REVENUE_DATA_SUCCESS = "EDIT_REVENUE_DATA_SUCCESS";
const EDIT_REVENUE_DATA_ERROR = "EDIT_REVENUE_DATA_ERROR";

// Target
const GET_TARGET_DATA_INIT = "GET_TARGET_DATA_INIT";
const GET_TARGET_DATA_SUCCESS = "GET_TARGET_DATA_SUCCESS";
const GET_TARGET_DATA_ERROR = "GET_TARGET_DATA_ERROR";

const ADD_TARGET_DATA_INIT = "ADD_TARGET_DATA_INIT";
const ADD_TARGET_DATA_SUCCESS = "ADD_TARGET_DATA_SUCCESS";
const ADD_TARGET_DATA_ERROR = "ADD_TARGET_DATA_ERROR";

const GET_TARGET_BY_ID_INIT = "GET_TARGET_BY_ID_INIT";
const GET_TARGET_BY_ID_SUCCESS = "GET_TARGET_BY_ID_SUCCESS";
const GET_TARGET_BY_ID_ERROR = "GET_TARGET_BY_ID_ERROR";

const EDIT_TARGET_DATA_INIT = "EDIT_TARGET_DATA_INIT";
const EDIT_TARGET_DATA_SUCCESS = "EDIT_TARGET_DATA_SUCCESS";
const EDIT_TARGET_DATA_ERROR = "EDIT_TARGET_DATA_ERROR";

// Authentication
const LOGIN_AUTHENTICATION_INIT = "LOGIN_AUTHENTICATION_INIT";
const LOGIN_AUTHENTICATION_SUCCESS = "LOGIN_AUTHENTICATION_SUCCESS";
const LOGIN_AUTHENTICATION_ERROR = "LOGIN_AUTHENTICATION_ERROR";

const LOGOUT_AUTHENTICATION_INIT = "LOGOUT_AUTHENTICATION_INIT";
const LOGOUT_AUTHENTICATION_SUCCESS = "LOGOUT_AUTHENTICATION_SUCCESS";
const LOGOUT_AUTHENTICATION_ERROR = "LOGOUT_AUTHENTICATION_ERROR";

// Hr Candidacy
const GET_HR_CANDIDACY_INIT = "GET_HR_CANDIDACY_INIT";
const GET_HR_CANDIDACY_SUCCESS = "GET_HR_CANDIDACY_SUCCESS";
const GET_HR_CANDIDACY_ERROR = "GET_HR_CANDIDACY_ERROR";

const GET_HR_CANDIDACY_BY_ID_INIT = "GET_HR_CANDIDACY_BY_ID_INIT";
const GET_HR_CANDIDACY_BY_ID_SUCCESS = "GET_HR_CANDIDACY_BY_ID_SUCCESS";
const GET_HR_CANDIDACY_BY_ID_ERROR = "GET_HR_CANDIDACY_BY_ID_ERROR";

const ADD_HR_CANDIDACY_INIT = "ADD_HR_CANDIDACY_INIT";
const ADD_HR_CANDIDACY_SUCCESS = "ADD_HR_CANDIDACY_SUCCESS";
const ADD_HR_CANDIDACY_ERROR = "ADD_HR_CANDIDACY_ERROR";


const ADD_HR_HOLIDAY_INIT ="ADD_HR_HOLIDAY_INIT";
const ADD_HR_HOLIDAY_SUCCESS ="ADD_HR_HOLIDAY_SUCCESS"; 
const ADD_HR_HOLIDAY_ERROR ="ADD_HR_HOLIDAY_ERROR";

const EDIT_HOLIDAY_DATA_INIT = "EDIT_HOLIDAY_DATA_INIT";
const EDIT_HOLIDAY_DATA_SUCCESS = "EDIT_HOLIDAY_DATA_SUCCESS";
const EDIT_HOLIDAY_DATA_ERROR = "EDIT_HOLIDAY_DATA_ERROR";

const GET_HOLIDAY_DATA_BY_ID_INIT = "GET_HOLIDAY_DATA_BY_ID_INIT";
const GET_HOLIDAY_DATA_BY_ID_SUCCESS = "GET_HOLIDAY_DATA_BY_ID_SUCCESS";
const GET_HOLIDAY_DATA_BY_ID_ERROR = "GET_HOLIDAY_DATA_BY_ID_ERROR";

const EDIT_HR_CANDIDACY_INIT = "EDIT_HR_CANDIDACY_INIT";
const EDIT_HR_CANDIDACY_SUCCESS = "EDIT_HR_CANDIDACY_SUCCESS";
const EDIT_HR_CANDIDACY_ERROR = "EDIT_HR_CANDIDACY_ERROR";

const EDIT_HR_CANDIDACY_STATUS_INIT = "EDIT_HR_CANDIDACY_STATUS_INIT";
const EDIT_HR_CANDIDACY_STATUS_SUCCESS = "EDIT_HR_CANDIDACY_STATUS_SUCCESS";
const EDIT_HR_CANDIDACY_STATUS_ERROR = "EDIT_HR_CANDIDACY_STATUS_ERROR";

const GET_HRS_AUTOCOMPLETE_INIT = "GET_HRS_AUTOCOMPLETE_INIT";
const GET_HRS_AUTOCOMPLETE_SUCCESS = "GET_HRS_AUTOCOMPLETE_SUCCESS";
const GET_HRS_AUTOCOMPLETE_ERROR = "GET_HRS_AUTOCOMPLETE_ERROR";

const GET_RESUME_DATA_INIT = "  GET_RESUME_DATA_INIT";
const GET_RESUME_DATA_SUCCESS = "GET_RESUME_DATA_SUCCESS";
const GET_RESUME_DATA_ERROR = "GET_RESUME_DATA_ERROR";

const IMPORT_CSV_HRFILE_INIT = "IMPORT_CSV_HRFILE_INIT";
const IMPORT_CSV_HRFILE_SUCCESS = "IMPORT_CSV_HRFILE_SUCCESS";
const IMPORT_CSV_HRFILE_ERROR = "IMPORT_CSV_HRFILE_ERROR";

// HRIS 
const GET_HRIS_INIT = "GET_HRIS_INIT";
const GET_HRIS_SUCCESS = "GET_HRIS_SUCCESS";
const GET_HRIS_ERROR = "GET_HRIS_ERROR";

const GET_HRIS_BY_ID_INIT = "GET_HRIS_BY_ID_INIT";
const GET_HRIS_BY_ID_SUCCESS = "GET_HRIS_BY_ID_SUCCESS";
const GET_HRIS_BY_ID_ERROR = "GET_HRIS_BY_ID_ERROR";

const ADD_HRIS_INIT = "ADD_HRIS_INIT";
const ADD_HRIS_SUCCESS = "ADD_HRIS_SUCCESS";
const ADD_HRIS_ERROR = "ADD_HRIS_ERROR";

const EDIT_HRIS_INIT = "EDIT_HRIS_INIT";
const EDIT_HRIS_SUCCESS = "EDIT_HRIS_SUCCESS";
const EDIT_HRIS_ERROR = "EDIT_HRIS_ERROR";

// Leave Management
const ADD_LEAVE_INIT = "ADD_LEAVE_INIT";
const ADD_LEAVE_SUCCESS = "ADD_LEAVE_SUCCESS";
const ADD_LEAVE_ERROR = "ADD_LEAVE_ERROR";

const GET_LEAVE_DATA_INIT = "GET_LEAVE_DATA_INIT";
const GET_LEAVE_DATA_SUCCESS = "GET_LEAVE_DATA_SUCCESS";
const GET_LEAVE_DATA_ERROR = "GET_LEAVE_DATA_ERROR";

const GET_LEAVE_DATA_BY_ID_INIT = "GET_LEAVE_DATA_BY_ID_INIT";
const GET_LEAVE_DATA_BY_ID_SUCCESS = "GET_LEAVE_DATA_BY_ID_SUCCESS";
const GET_LEAVE_DATA_BY_ID_ERROR = "GET_LEAVE_DATA_BY_ID_ERROR";


const EDIT_LEAVE_DATA_INIT = "EDIT_LEAVE_DATA_INIT";
const EDIT_LEAVE_DATA_SUCCESS = "EDIT_LEAVE_DATA_SUCCESS";
const EDIT_LEAVE_DATA_ERROR = "EDIT_LEAVE_DATA_ERROR";

const EDIT_LEAVE_STATUS_INIT = "EDIT_LEAVE_STATUS_INIT";
const EDIT_LEAVE_STATUS_SUCCESS = "EDIT_LEAVE_STATUS_SUCCESS";
const EDIT_LEAVE_STATUS_ERROR = "EDIT_LEAVE_STATUS_ERROR";

// JOB VACANCY Management
const ADD_VACANCY_INIT = "ADD_VACANCY_INIT";
const ADD_VACANCY_SUCCESS = "ADD_VACANCY_SUCCESS";
const ADD_VACANCY_ERROR = "ADD_VACANCY_ERROR";

const GET_VACANCY_DATA_INIT = "GET_VACANCY_DATA_INIT";
const GET_VACANCY_DATA_SUCCESS = "GET_VACANCY_DATA_SUCCESS";
const GET_VACANCY_DATA_ERROR = "GET_VACANCY_DATA_ERROR";

const GET_VACANCY_DATA_BY_ID_INIT = "GET_VACANCY_DATA_BY_ID_INIT";
const GET_VACANCY_DATA_BY_ID_SUCCESS = "GET_VACANCY_DATA_BY_ID_SUCCESS";
const GET_VACANCY_DATA_BY_ID_ERROR = "GET_VACANCY_DATA_BY_ID_ERROR";

const EDIT_VACANCY_DATA_INIT = "EDIT_VACANCY_DATA_INIT";
const EDIT_VACANCY_DATA_SUCCESS = "EDIT_VACANCY_DATA_SUCCESS";
const EDIT_VACANCY_DATA_ERROR = "EDIT_VACANCY_DATA_ERROR";

const GET_HR_TARGET_BY_ID_INIT = "GET_HR_TARGET_BY_ID_INIT";
const GET_HR_TARGET_BY_ID_SUCCESS = "GET_HR_TARGET_BY_ID_SUCCESS";
const GET_HR_TARGET_BY_ID_ERROR = "GET_HR_TARGET_BY_ID_ERROR";

// Dashboard Module
const GET_DOB_DEPT_DATA_INIT = "GET_DOB_DEPT_DATA_INIT";
const GET_DOB_DEPT_DATA_SUCCESS = "GET_DOB_DEPT_DATA_SUCCESS";
const GET_DOB_DEPT_DATA_ERROR = "GET_DOB_DEPT_DATA_ERROR";

const GET_TIMELOGTODAY_DATA_INIT = "GET_TIMELOGTODAY_DATA_INIT";
const GET_TIMELOGTODAY_DATA_SUCCESS = "GET_TIMELOGTODAY_DATA_SUCCESS";
const GET_TIMELOGTODAY_DATA_ERROR = "GET_TIMELOGTODAY_DATA_ERROR";

const DELETE_HOLIDAY_STATUS_INIT =  "DELETE_HOLIDAY_STATUS_INIT";
const DELETE_HOLIDAY_STATUS_SUCCESS =  "DELETE_HOLIDAY_STATUS_SUCCESS"; 
const DELETE_HOLIDAY_STATUS_ERROR =  "DELETE_HOLIDAY_STATUS_ERROR";

// PROJECT MANAGEMENT Module
const GET_PROJECT_DATA_INIT = "GET_PROJECT_DATA_INIT";
const GET_PROJECT_DATA_SUCCESS = "GET_PROJECT_DATA_SUCCESS";
const GET_PROJECT_DATA_ERROR = "GET_PROJECT_DATA_ERROR";

const GET_PROJECTS_BY_ID_INIT="GET_PROJECTS_BY_ID_INIT";
const GET_PROJECTS_BY_ID_SUCCESS="GET_PROJECTS_BY_ID_SUCCESS";
const GET_PROJECTS_BY_ID_ERROR="GET_PROJECTS_BY_ID_ERROR";

const ADD_PRO_TASK_INIT="ADD_PRO_TASK_INIT";
const ADD_PRO_TASK_SUCCESS="ADD_PRO_TASK_SUCCESS";
const ADD_PRO_TASK_ERROR="ADD_PRO_TASK_ERROR";

const UPDATE_PROJECT_INIT="UPDATE_PROJECT_INIT";
const UPDATE_PROJECT_SUCCESS="UPDATE_PROJECT_SUCCESS";
const UPDATE_PROJECT_ERROR="UPDATE_PROJECT_ERROR";

const GET_MONTHLY_DATA_INIT = "GET_MONTHLY_DATA_INIT";
const GET_MONTHLY_DATA_SUCCESS = "GET_MONTHLY_DATA_SUCCESS";
const GET_MONTHLY_DATA_ERROR = "GET_MONTHLY_DATA_ERROR";

export {
  GET_USERS_DATA_INIT,
  GET_USERS_DATA_SUCCESS,
  GET_USERS_DATA_ERROR,

  GET_USERS_DEPARTMENTS_INIT,
  GET_USERS_DEPARTMENTS_SUCCESS,
  GET_USERS_DEPARTMENTS_ERROR,

  ADD_USERS_DATA_INIT,
  ADD_USERS_DATA_SUCCESS,
  ADD_USERS_DATA_ERROR,

  EDIT_USERS_INIT,
  EDIT_USERS_SUCCESS,
  EDIT_USERS_ERROR,

  GET_USERS_PERMISSION_INIT,
  GET_USERS_PERMISSION_SUCCESS,
  GET_USERS_PERMISSION_ERROR,

  UPDATE_USERS_INIT,
  UPDATE_USERS_SUCCESS,
  UPDATE_USERS_ERROR,

  IMPORT_PIC_FILE_INIT,
  IMPORT_PIC_FILE_SUCCESS,
  IMPORT_PIC_FILE_ERROR,

  GET_USERS_AUTOCOMPLETE_INIT,
  GET_USERS_AUTOCOMPLETE_SUCCESS,
  GET_USERS_AUTOCOMPLETE_ERROR,

  UPDATE_USER_ISACTIVE_INIT,
  UPDATE_USER_ISACTIVE_SUCCESS,
  UPDATE_USER_ISACTIVE_ERROR,

  // Department Module
  GET_DEPARTMENTS_INIT,
  GET_DEPARTMENTS_SUCCESS,
  GET_DEPARTMENTS_ERROR, 
  
  ADD_DEPARTMENTS_INIT,
  ADD_DEPARTMENTS_SUCCESS,
  ADD_DEPARTMENTS_ERROR,
  
  GET_DEPARTMENTS_BY_ID_INIT,
  GET_DEPARTMENTS_BY_ID_SUCCESS,
  GET_DEPARTMENTS_BY_ID_ERROR,

  EDIT_DEPARTMENTS_INIT,
  EDIT_DEPARTMENTS_SUCCESS,
  EDIT_DEPARTMENTS_ERROR,

 UPDATE_DEPT_ISACTIVE_INIT ,
 UPDATE_DEPT_ISACTIVE_SUCCESS ,
 UPDATE_DEPT_ISACTIVE_ERROR ,

// Performance Main Parameter
  GET_PERFORMANCE_INIT,
  GET_PERFORMANCE_SUCCESS,
  GET_PERFORMANCE_ERROR,

  ADD_PERFORMANCE_INIT,
  ADD_PERFORMANCE_SUCCESS,
  ADD_PERFORMANCE_ERROR,

  GET_PERFORMANCE_BY_ID_INIT,
  GET_PERFORMANCE_BY_ID_SUCCESS,
  GET_PERFORMANCE_BY_ID_ERROR,

  EDIT_PERFORMANCE_INIT,
  EDIT_PERFORMANCE_SUCCESS,
  EDIT_PERFORMANCE_ERROR,

  UPDATE_PER_ISACTIVE_INIT ,
  UPDATE_PER_ISACTIVE_SUCCESS ,
  UPDATE_PER_ISACTIVE_ERROR ,

// Sub Performance
  GET_SUBPERFORMANCE_INIT,
  GET_SUBPERFORMANCE_SUCCESS,
  GET_SUBPERFORMANCE_ERROR,

  ADD_SUBPERFORMANCE_INIT,
  ADD_SUBPERFORMANCE_SUCCESS,
  ADD_SUBPERFORMANCE_ERROR,

  GET_SUBPERFORMANCE_BY_ID_INIT,
  GET_SUBPERFORMANCE_BY_ID_SUCCESS,
  GET_SUBPERFORMANCE_BY_ID_ERROR,

  EDIT_SUBPERFORMANCE_INIT,
  EDIT_SUBPERFORMANCE_SUCCESS,
  EDIT_SUBPERFORMANCE_ERROR,

// Evaluation
  GET_CALCULATION_INIT,
  GET_CALCULATION_SUCCESS,
  GET_CALCULATION_ERROR,

  SAVE_CALCULATION_INIT,
  SAVE_CALCULATION_SUCCESS,
  SAVE_CALCULATION_ERROR,

// Mom Modules
  GET_MOM_INIT,
  GET_MOM_SUCCESS,
  GET_MOM_ERROR,

  SUBMIT_MOM_INIT,
  SUBMIT_MOM_SUCCESS,
  SUBMIT_MOM_ERROR,

  EDIT_MOM_DATA_INIT,
  EDIT_MOM_DATA_SUCCESS,
  EDIT_MOM_DATA_ERROR,

// Time Log
  ADD_CHECKIN_INIT,
  ADD_CHECKIN_SUCCESS,
  ADD_CHECKIN_ERROR,

  UPDATE_CHECKOUT_INIT,
  UPDATE_CHECKOUT_SUCCESS,
  UPDATE_CHECKOUT_ERROR,
  
  GET_TIME_TABLE_INIT,
  GET_TIME_TABLE_SUCCESS,
  GET_TIME_TABLE_ERROR,

  // Sales Module
  PROPOSAL_SUBMISSION_INIT,
  PROPOSAL_SUBMISSION_SUCCESS,
  PROPOSAL_SUBMISSION_ERROR,

  POST_PROPOSAL_SUBMIT_INIT,
  POST_PROPOSAL_SUBMIT_SUCCESS,
  POST_PROPOSAL_SUBMIT_ERROR,

  GET_PROPOSAL_BY_ID_INIT,
  GET_PROPOSAL_BY_ID_SUCCESS,
  GET_PROPOSAL_BY_ID_ERROR,
  
  UPLOAD_PROPOSAL_INIT,
  UPLOAD_PROPOSAL_SUCCESS,
  UPLOAD_PROPOSAL_ERROR,

  UPDATE_STATUS_INIT,
  UPDATE_STATUS_SUCCESS,
  UPDATE_STATUS_ERROR,

  GET_SALES_DROPDOWN_INIT,
  GET_SALES_DROPDOWN_SUCCESS,
  GET_SALES_DROPDOWN_ERROR,

  BUTTON_SELECT_STATUS_INIT,
  BUTTON_SELECT_STATUS_SUCCESS,
  BUTTON_SELECT_STATUS_ERROR,

  DELETE_ACTIVE_STATUS_INIT,
  DELETE_ACTIVE_STATUS_SUCCESS,
  DELETE_ACTIVE_STATUS_ERROR,

  GET_SALES_TARGET_INIT,
  GET_SALES_TARGET_SUCCESS,
  GET_SALES_TARGET_ERROR,

  IMPORT_CSV_FILE_INIT,
  IMPORT_CSV_FILE_SUCCESS,
  IMPORT_CSV_FILE_ERROR,

  GET_SALES_TARGET_BY_ID_INIT,
  GET_SALES_TARGET_BY_ID_SUCCESS,
  GET_SALES_TARGET_BY_ID_ERROR,

  //Revenue Report
  GET_REVENUE_DATA_INIT,
  GET_REVENUE_DATA_SUCCESS,
  GET_REVENUE_DATA_ERROR,

  ADD_REVENUE_DATA_INIT,
  ADD_REVENUE_DATA_SUCCESS,
  ADD_REVENUE_DATA_ERROR,

  GET_REVENUE_BY_ID_INIT,
  GET_REVENUE_BY_ID_SUCCESS,
  GET_REVENUE_BY_ID_ERROR,

  EDIT_REVENUE_DATA_INIT,
  EDIT_REVENUE_DATA_SUCCESS,
  EDIT_REVENUE_DATA_ERROR,

  //Target
  GET_TARGET_DATA_INIT,
  GET_TARGET_DATA_SUCCESS,
  GET_TARGET_DATA_ERROR,

  ADD_TARGET_DATA_INIT,
  ADD_TARGET_DATA_SUCCESS,
  ADD_TARGET_DATA_ERROR,

  GET_TARGET_BY_ID_INIT,
  GET_TARGET_BY_ID_SUCCESS,
  GET_TARGET_BY_ID_ERROR,

  EDIT_TARGET_DATA_INIT,
  EDIT_TARGET_DATA_SUCCESS,
  EDIT_TARGET_DATA_ERROR,  

  // Authentication
  LOGIN_AUTHENTICATION_INIT,
  LOGIN_AUTHENTICATION_SUCCESS,
  LOGIN_AUTHENTICATION_ERROR,
  
 LOGOUT_AUTHENTICATION_INIT,
 LOGOUT_AUTHENTICATION_SUCCESS,
 LOGOUT_AUTHENTICATION_ERROR,
 
  // Hr Candidacy
  GET_HR_CANDIDACY_INIT,
  GET_HR_CANDIDACY_SUCCESS,
  GET_HR_CANDIDACY_ERROR,

  GET_HR_CANDIDACY_BY_ID_INIT,
  GET_HR_CANDIDACY_BY_ID_SUCCESS,
  GET_HR_CANDIDACY_BY_ID_ERROR,

  ADD_HR_CANDIDACY_INIT,
  ADD_HR_CANDIDACY_SUCCESS,
  ADD_HR_CANDIDACY_ERROR,

  ADD_HR_HOLIDAY_INIT,
  ADD_HR_HOLIDAY_SUCCESS, 
  ADD_HR_HOLIDAY_ERROR,

  EDIT_HOLIDAY_DATA_INIT,
  EDIT_HOLIDAY_DATA_SUCCESS,
  EDIT_HOLIDAY_DATA_ERROR,

  GET_HOLIDAY_DATA_BY_ID_INIT,
  GET_HOLIDAY_DATA_BY_ID_SUCCESS,
  GET_HOLIDAY_DATA_BY_ID_ERROR,

  EDIT_HR_CANDIDACY_INIT,
  EDIT_HR_CANDIDACY_SUCCESS,
  EDIT_HR_CANDIDACY_ERROR,

  EDIT_HR_CANDIDACY_STATUS_INIT,
  EDIT_HR_CANDIDACY_STATUS_SUCCESS,
  EDIT_HR_CANDIDACY_STATUS_ERROR,

  GET_HRS_AUTOCOMPLETE_INIT,
  GET_HRS_AUTOCOMPLETE_SUCCESS,
  GET_HRS_AUTOCOMPLETE_ERROR,

  GET_RESUME_DATA_INIT,
  GET_RESUME_DATA_SUCCESS,
  GET_RESUME_DATA_ERROR,

  IMPORT_CSV_HRFILE_INIT,
  IMPORT_CSV_HRFILE_SUCCESS,
  IMPORT_CSV_HRFILE_ERROR,

  //HRIS
  GET_HRIS_INIT,
  GET_HRIS_SUCCESS,
  GET_HRIS_ERROR,

  GET_HRIS_BY_ID_INIT,
  GET_HRIS_BY_ID_SUCCESS,
  GET_HRIS_BY_ID_ERROR,

  ADD_HRIS_INIT,
  ADD_HRIS_SUCCESS,
  ADD_HRIS_ERROR,

  EDIT_HRIS_INIT,
  EDIT_HRIS_SUCCESS,
  EDIT_HRIS_ERROR,

  // Leave Management
  ADD_LEAVE_INIT,
  ADD_LEAVE_SUCCESS,
  ADD_LEAVE_ERROR,

  GET_LEAVE_DATA_INIT,
  GET_LEAVE_DATA_SUCCESS,
  GET_LEAVE_DATA_ERROR,

  GET_LEAVE_DATA_BY_ID_INIT,
  GET_LEAVE_DATA_BY_ID_SUCCESS,
  GET_LEAVE_DATA_BY_ID_ERROR,

  EDIT_LEAVE_DATA_INIT,
  EDIT_LEAVE_DATA_SUCCESS,
  EDIT_LEAVE_DATA_ERROR,

  EDIT_LEAVE_STATUS_INIT,
  EDIT_LEAVE_STATUS_SUCCESS,
  EDIT_LEAVE_STATUS_ERROR,

 

  // JOB VACANCY Management
  ADD_VACANCY_INIT,
  ADD_VACANCY_SUCCESS,
  ADD_VACANCY_ERROR,
  
  GET_VACANCY_DATA_INIT,
  GET_VACANCY_DATA_SUCCESS,
  GET_VACANCY_DATA_ERROR,
  
  GET_VACANCY_DATA_BY_ID_INIT,
  GET_VACANCY_DATA_BY_ID_SUCCESS,
  GET_VACANCY_DATA_BY_ID_ERROR,
  
  EDIT_VACANCY_DATA_INIT,
  EDIT_VACANCY_DATA_SUCCESS,
  EDIT_VACANCY_DATA_ERROR,

  GET_HR_TARGET_BY_ID_INIT,
  GET_HR_TARGET_BY_ID_SUCCESS,
  GET_HR_TARGET_BY_ID_ERROR,

  // Dashboard Module
  GET_DOB_DEPT_DATA_INIT,
  GET_DOB_DEPT_DATA_SUCCESS,
  GET_DOB_DEPT_DATA_ERROR ,

  GET_TIMELOGTODAY_DATA_INIT,
  GET_TIMELOGTODAY_DATA_SUCCESS,
  GET_TIMELOGTODAY_DATA_ERROR ,

  DELETE_HOLIDAY_STATUS_INIT,
  DELETE_HOLIDAY_STATUS_SUCCESS, 
  DELETE_HOLIDAY_STATUS_ERROR,

  // PROJECT MANAGEMENT Module
  GET_PROJECT_DATA_INIT,
  GET_PROJECT_DATA_SUCCESS,
  GET_PROJECT_DATA_ERROR,

  GET_PROJECTS_BY_ID_INIT,
  GET_PROJECTS_BY_ID_SUCCESS,
  GET_PROJECTS_BY_ID_ERROR,
  
  ADD_PRO_TASK_INIT,
  ADD_PRO_TASK_SUCCESS,
  ADD_PRO_TASK_ERROR,

  UPDATE_PROJECT_INIT,
  UPDATE_PROJECT_SUCCESS,
  UPDATE_PROJECT_ERROR,

  GET_MONTHLY_DATA_INIT,
  GET_MONTHLY_DATA_SUCCESS,
  GET_MONTHLY_DATA_ERROR,
};
